services:

  web_ui:
    build:
      context: ./web_ui
      dockerfile: Dockerfile_webui
    ports:
      - "${WEB_UI_EXPOSED_PORT}:7860"
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile_api
    volumes:
      - img_store:/img_store
    ports:
      - "${WEB_API_EXPOSED_PORT}:8000"
    env_file: 
      - ./container_configs.env
    depends_on:
      - redis
  
  redis:
    image: "redis:alpine"
    # redis uses the default port 6379,
    # and is not exposed to the host machine
    # so it can only be accessed by other containers
    # in the same network
  
  inference:
    build: 
      context: ./inference
      dockerfile: Dockerfile_inference
    volumes:
      - img_store:/img_store
    env_file:
      - ./container_configs.env
    # similar to redis, inference is not exposed to the host machine
    depends_on:
      - redis    


volumes:
  img_store: